import type {NextPage} from 'next';
import {useEffect, useState} from 'react';
import Head from 'next/head';
import ScrollMenu from '../components/Menu/ScrollMenu';
import styles from '../styles/Home.module.css';
import {subscribe, getStore, dispatch} from 'imus';
import useStore from '../hooks/useStore';

const Home: NextPage = () => {
    const {tabs, tabActive, createTab, updateTab, changeTab} = useStore();
    const [textAreaContent, setTextAreaContent] = useState('');

    const handleTabClick = (tabId: number) => {
        changeTab(+tabId);
    };

    useEffect(() => {
        if (tabs.length === 0 || !tabs) return;
        const found = tabs.find((tab) => tab.id === tabActive);
        if (found) setTextAreaContent(found.content);
    }, [tabs, tabActive]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Notee</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.mainItem}>
                    {tabs.length > 0 && (
                        <ScrollMenu
                            items={tabs}
                            handleClickTab={handleTabClick}
                        />
                    )}
                    <button onClick={() => createTab()}>+</button>
                </div>
                <div className={styles.mainItem}>Browser offline</div>
            </main>
            <textarea
                value={textAreaContent}
                onChange={(e) => updateTab(tabActive, e.target.value)}
            ></textarea>
        </div>
    );
};

export default Home;
